#!/bin/bash

if [ $# -ne 2 ]
then
	echo 'Usage rename [old_name] [new name]'
fi

old_name=$1
new_name=$2

for file in `ls`
do
	filename=`echo $file | cut -d '.' -f 1`
	extension=`echo $file | cut -d '.' -f 2`

	if [ ${filename} == ${old_name} ]
	then
		mv ${file} ${new_name}.${extension}
		echo "mv ${file} ${new_name}.${extension}"
	fi
done

